### PR TITLE
Allow to select which Geocoding provider to use

### PR DESCRIPTION
**Pull request by jeromelebleu**
It adds OpenStreetMap Nominatim Geocoding provider and allows to select which one to use to geocode addresses.

To make it possible, a new type `selects` has been added to the **defaults** property for which choices are retrieved from the new **choices** property - the key must be the same in both arrays.

### CODE REVIEW

**Comment by jeromelebleu** [comment]
Do you plan to purpose your changes to the original plugin at some times? Or is it a new plugin? In order to know if I also have to create this pull request for Leaflet Map in case not... Thanks!

**Comment by nielsalstrup** [comment]
No plans for reintroducing my changes in the original plugin. My changes are somewhat specialized - concerns a specific Danish address-service (DAWA).

**Comment by jeromelebleu** [comment]
Okay I understand, so are you interested by this pull request? I should maybe let DAWA as the default Geocoding provider in that case...

**Comment by jeromelebleu** [comment]
I think it's a shame all the same that it's not reintroduced to the original plugin since it doesn't make things easy to purpose pull requests in both plugins and share their features... But it's up to you, I respect your choice! :)

**Pull request merged**
